# Generated by Django 3.1.5 on 2021-01-13 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simple_api', '0002_auto_20210112_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_activity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
