# Generated by Django 3.1.5 on 2021-01-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_api', '0003_user_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
