# Generated by Django 3.1.5 on 2021-01-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_api', '0004_auto_20210113_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post_dislike',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post_like',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
